### ISSUE TITLE
Arbitrary File Write using lax HEAD regex allowing path traversal

### ISSUE THREAD

**Issue by JorianWoltjer** [holly-hacker/git-dumper#11]
In the RegEx below, the path in the HEAD file of git is validated:
https://github.com/holly-hacker/git-dumper/blob/main/src/git_parsing.rs#L8

It must start with `refs/heads/` and the following characters must not be whitespace (`\S+`). This validation is not enough to prevent sequences like `../` from appearing, allowing path traversal. If a server responds to a request for its `.git/HEAD` endpoint with a response like the following:

```
ref: refs/heads/../../../../../../../tmp/pwned
```

Then the path above is added to the queue:
https://github.com/holly-hacker/git-dumper/blob/main/src/dump_git.rs#L162-L168

When the time comes, this path is taken off the queue and downloaded from the same web server again. Responding to `.git/refs/heads/../../../../../../../tmp/pwned` with some arbitrary content will then make this tool write the returned content to the `/tmp/pwned` file:
https://github.com/holly-hacker/git-dumper/blob/main/src/dump_git.rs#L76-L90

To prevent issues like these in the future, one safe solution would be to resolve the path fully before writing the file (evaluating any path traversals etc.), and then checking if it still starts with the expected `.git` local path. Only if the path is still contained in this directory, is it safe to write.
Alternatively, you could fix this one issue by disallowing `../` and `..\` in the paths returned from the HEAD file.

**Comment by holly-hacker** [comment]
Thanks for the report! This is my first time being on the receiving side of a security report, so it's certainly an interesting experience :)

I'll written up a patch that disallows any `..` segments which should block any path traversal attempts, which you can see in commit 273e2951562bcb27f0fe5685b6c981f127868def. Could you check this out and confirm that this fixes the issue?

If you confirm this adequately fixes the issue, I'll create a new v1.0.1 release and yank the current v1.0.0 from crates.io.

**Comment by holly-hacker** [comment]
In the interest of getting a patch out, I'll assume this works for now. Please confirm when you have the time.

**Comment by JorianWoltjer** [comment]
Looks good to me! Thanks for the quick fix
